### ISSUE TITLE
Error messages leak from one row to the other

### ISSUE THREAD

**Issue by mtylty** [solidusio-contrib/solidus_importer#35]
It looks like error messages and status are leaked from one row to the other. In the screenshot below 713 is invalid but 714 is valid.

<img width="355" alt="Schermata 2020-08-31 alle 17 15 06" src="https://user-images.githubusercontent.com/167670/91736131-86b37980-ebad-11ea-8417-707830226330.png">

In the messages section they both show the same error (the one generated by 713).

I think this could be related to this [piece of code](https://github.com/solidusio-contrib/solidus_importer/blob/master/lib/solidus_importer/process_row.rb#L15) because the `merge!` will keep the error data for future rows.

**Comment by MinasMazar** [comment]
This has been resolved by #38.
