### ISSUE TITLE
Missing option_type

### ISSUE THREAD

**Issue by conghuy1007** [solidusio-contrib/solidus_importer#48]
I try to import 2 products, with Size and Color attributes. I check the first product with no problems, the second product can't see variants because it can't load option_type. I think the reason is probably due to the duplicate attribute, so I can't create a new option_type

![Screenshot from 2021-01-12 09-05-27](https://user-images.githubusercontent.com/47658870/104260839-d2105980-54b6-11eb-8570-65ba0ed827a5.png)
![Screenshot from 2021-01-12 09-19-13](https://user-images.githubusercontent.com/47658870/104261047-45b26680-54b7-11eb-9d3b-13d30343a6df.png)

**Comment by elia** [comment]
Which version are you using? 
Can you please provide the CSV (even an obfuscated version would work, the there's sensitive data) so we can reproduce the problem?

**Comment by conghuy1007** [comment]
I using version 0.1.0, i try bundle version 0.2.0 but it has error missing gem. My file using to test
[products_export.zip](https://github.com/solidusio-contrib/solidus_importer/files/5806203/products_export.zip)

**Comment by conghuy1007** [comment]
I tried to overwrite 2 files solidus_importer / lib / solidus_importer / processors / option_types.rb and solidus_importer / lib / solidus_importer / processors / option_values.rb then solved this problem

**Comment by kennyadsl** [comment]
@conghuy1007 thanks for reporting back! Can you please share your findings with us? We'd like to improve the developer experience and knowing what wasn't working for you and how you fixed the issue would be pretty helpful. 🙏
